
#ifndef SYSDEFS_H
#define SYSDEFS_H
/* ********************** FILE HEADER *************************************
*  System Definitions and Macros
*  For Freescale ColdFire Architectures
*  Adopted from Ilialex AVR Library
*
*  DESCRIPTION
*  Standard definitions
*
*  CONTRIBUTOR TAGS
*      AI - Alexopoulos Ilias
*
*  HISTORY:
* 2010 Aug 12:     [AI] Created This File
*
*
****************************************************************************/

/* normally the below settings should be imported from the makefile */
/* For initial development these are ported here */
#define c_TimeSlice_Hz  	1000                 	/*!< Time Slice depends on CPU speed and clock settings. Set by PE */
#define c_VEROS         	120              		/*!< OS version, Should be Set by Makefile */
#define c_VERBL         	400              		/*!< BootLoader Version, Should be Set by Makefile */
#define c_DATEBL			2024-03-13				/*!< BootLoader Date, Should be Set by Makefile */

/* Alive Led Indications Set */
#define   c_ALIVEOK_ms       500   					/*!< Alive LED interval When Ok */
#define   c_ALIVESER_ms      125   					/*!< Alive LED interval When Serial Error */

/* Systick SW Timers max (should be > 7) */
#define c_TIMERSWMAX        	8					/*!< Maximum Software timers support */

/* Timed Tasks interval */
#define c_AppInterval_ms        50				/*!< >7.81 in order to avoid div/0 */
#define c_ADCInterval_ms        20				/*!< ADC sampling interval */
#define c_SensorInterval_ms		50				/*!< Sensor sampling interval */
#define c_NVMgmntInterval_ms	100				/*!< Non-Volatile Management periodic operation */
#define c_L1ActInterval_ms		50				/*!< L1 LED Activation period */
#define c_L3ActInterval_ms		50				/*!< L3 LED Activation period */
#define c_ErrorInterval_ms		100				/*!< Error LED Activation period */

#define c_CommActivity_ms		10				/*!< Communication Activity LED delay */

/* Debug on HW pins (SWSPI) */
#define c_DBG_LINKL3_ENA		0
#define c_DBG_BLAPP_ENA			0

/*****************************************
Internal Parameters, do not change
*****************************************/

// Version Settings
#define c_VEROSSTR "\nSTM32F4 OS " XSTR(c_VEROS)" started...\r\n"
#define c_VERBLSTR "BL Version " XSTR(c_VERBL) "\r\n"

/* Burster Query L1 Command */
// Automatically generated by makefile

/* #include "..\build_obj\Version.h" */
#define c_VERSION XSTR(c_DATEBL) " V"XSTR(c_VERBL) " ILOT L2C BootLdr"

#ifndef c_VERSION
#error "No Version Information"
#endif



/* SysTick SW Timer Assignment */
/* Timer Activation (0: Stop, >0: Run) */
#define c_TIMER_EXECWAIT	0		/*!< Systick Timer allocated for Time Wait */
#define c_TIMER_LinkL3		1		/*!< Link L3 Timeout SW Timer */
#define c_TIMER_LinkL1		2		/*!< Link L1 Timeout SW Timer */
#define c_TIMER_LED			4		/*!< Comm LED timer 			*/
#define c_TIMER_EventTask	6		/*!< Event task periodic timer (event pace) */

\


/* MCU Address Space, values for STM32F452 */
/* Total Flash memory */
#define FLASH_ADDRESS_ALL_MIN       0x08000000
#define FLASH_ADDRESS_ALL_MAX       0x0807FFFF

#define MEMSPACE_BL					0x20000
#define MEMSPACE_APP				0x2F000
#define MEMSPACE_CFG				0x00800

#define FLASH_ADDRESS_BL_MIN		FLASH_ADDRESS_ALL_MIN
#define FLASH_ADDRESS_BL_MAX		FLASH_ADDRESS_ALL_MIN + MEMSPACE_BL - 1

/* Application space 1, 138KB */
#define FLASH_ADDRESS_APP1_MIN      FLASH_ADDRESS_BL_MAX + 1
#define FLASH_ADDRESS_APP1_MAX      FLASH_ADDRESS_APP1_MIN + MEMSPACE_APP - 1

/* Application space 2, 138KB */
#define FLASH_ADDRESS_APP2_MIN      FLASH_ADDRESS_APP1_MAX + 1
#define FLASH_ADDRESS_APP2_MAX      FLASH_ADDRESS_APP2_MIN + MEMSPACE_APP - 1

/* Configuration space, 2KBx2 */
#define FLASH_ADDRESS_CFG1_MIN       FLASH_ADDRESS_ALL_MAX - MEMSPACE_CFG*2 + 1
#define FLASH_ADDRESS_CFG1_MAX       FLASH_ADDRESS_ALL_MAX
#define FLASH_ADDRESS_CFG2_MIN       FLASH_ADDRESS_ALL_MAX - MEMSPACE_CFG + 1
#define FLASH_ADDRESS_CFG2_MAX       FLASH_ADDRESS_ALL_MAX

/* RAM block, 128KB */
#define RAM_ADDRESS_1_MIN		 0x20000000
#define RAM_ADDRESS_1_MAX		 0x2001FFFF

#define c_PAGE_SIZE_Bytes		2048		/*!< STM32F452 */

#define FLASH_PROTECTED_ADDRESS  0x08003FFF
#define FLASH_ADDR_OFFSET		 0x44000000

#define c_DATARECORDLEN		64

// Bootloader definitions
#define c_BLVERMAJ				0x03		// Major bootloader version (in hex)
#define c_BLVERMIN				0x00		// Minor Bootloader version (in hex)


#define c_TIMEWAIT_ms			20000UL			// Wait 8sec before jump to APP.
#define c_USBWAIT_ms			1000UL			// Wait 2sec before jump to APP.

#define _INLINE_ inline

#define STR(x) #x
#define XSTR(x) STR(x)



/*************** SysStat Register ******************/
#define b_SysTick	    	0
#define b_DBG				1
#define b_AppTick	    	2
#define b_ADCTick	    	3
#define b_LCDBusy	    	4
#define b_LedAlive    		5
#define b_SPIActive    		6
#define b_ApplicSensorTick 	10
#define b_DbgRawInput		11
#define b_NVMgmnt			12
#define b_ApplicSensTPTick	13


// Computed values for systick
#define c_SYSTIMEMAX            1000 /* c_TimeSlice_Hz */
#define c_SysTickPeriod_ms        (1000.0/c_TimeSlice_Hz)		/* 1mS period */

#define c_ALIVEOK_ticks          (INT16U) (c_ALIVEOK_ms / c_SysTickPeriod_ms)    /* Alive LED When Ok */
#define c_ALIVESER_ticks         (INT16U) (c_ALIVESER_ms / c_SysTickPeriod_ms)   /* Alive LED When Serial Error */

#define c_APP_ticks             (INT16U) (c_AppInterval_ms / c_SysTickPeriod_ms)
#define c_L1Act_ticks			(INT8U) (c_L1ActInterval_ms / c_SysTickPeriod_ms )
#define c_L3Act_ticks			(INT8U) (c_L3ActInterval_ms / c_SysTickPeriod_ms )
#define c_ERR_ticks				(INT8U) (c_ErrorInterval_ms / c_SysTickPeriod_ms )
#define c_SensorInterval_ticks	(INT8U) (c_SensorInterval_ms / c_SysTickPeriod_ms )






/* Uart L1 Status */
#define c_UART_ERROK			0		/*!< Everything fine */
#define c_UARTRxFrmErr			1		/*!< Receiver Frame Error */
#define c_UARTRxOvrErr			2		/*!< Receiver Overrun Error */

#define c_UART_ERRTxIdle		0		/*!< Tx idle, finished ok */
#define c_UART_ERRRxIdle		0		/*!< Rx idle, not receiving, inactive	*/
#define c_UART_ERRTxActive		1		/*!< Tx still active */
#define c_UART_ERRRxActive		1		/*!< Rx still active, receiving (RTS on) */
#define c_UART_ERRRxPacket		2		/*!< Rx Packet Received Ok, stop Reception */
#define c_UART_ERRRxError		3		/*!< Rx with Errors, stop Reception */
#define c_UART_ERRRxEnabled		4		/*!< Rx still active, idle */

#define c_L3SOP		0xFF
#define c_L3EOP		0xFE
#define c_L3ESC		0xFD

#define c_L1SOP		'{'
#define c_L1EOP		'}'


#endif // ifndef SYSDEFS_H
